# Semantic Enhancement Blueprint
# Defines how to integrate embeddings and semantic search with blueprint-generated tools

metadata:
  name: "Semantic Enhancement Configuration"
  version: "1.0"
  description: "Configuration for hybrid semantic search capabilities in blueprint-generated tools"
  purpose: "Enable semantic intelligence while maintaining blueprint-driven architecture"

# Global semantic search configuration
semantic_config:
  # Embedding model configuration
  embedding_model: "text-embedding-3-large"
  embedding_dimensions: 3072
  
  # Search thresholds and parameters
  similarity_threshold: 0.5
  semantic_boost_factor: 1.2  # How much to boost semantic results vs SQL results
  max_semantic_results: 20    # Max results from semantic search before filtering
  
  # Query enhancement settings
  query_enhancement:
    enabled: true
    max_expansion_terms: 5      # Max additional terms to add to query
    min_similarity_for_expansion: 0.6  # Min similarity to include expansion term
    
  # Hybrid search strategy
  hybrid_strategy: "enhanced_sql"  # Options: "enhanced_sql", "semantic_first", "parallel_merge"

# Per-tool semantic enhancement configuration
tool_enhancements:
  # Document search tools get full semantic search
  search_academic_documents:
    semantic_enabled: true
    enhancement_type: "hybrid_search"
    semantic_weight: 0.6
    sql_weight: 0.4
    query_expansion: true
    fallback_to_sql: true
    
  search_chronicle_documents:
    semantic_enabled: true
    enhancement_type: "hybrid_search"
    semantic_weight: 0.7  # Personal notes benefit more from semantic understanding
    sql_weight: 0.3
    query_expansion: true
    fallback_to_sql: true
    
  # Topic search gets semantic expansion for better concept discovery
  search_topics:
    semantic_enabled: true
    enhancement_type: "query_expansion"
    expansion_source: "topics"  # Use topic embeddings to expand search terms
    max_expansions: 3
    fallback_to_sql: true
    
  # Entity searches get limited semantic enhancement
  search_people:
    semantic_enabled: true
    enhancement_type: "query_expansion"
    expansion_source: "people"
    max_expansions: 2
    
  search_methods:
    semantic_enabled: true
    enhancement_type: "query_expansion"
    expansion_source: "methods"
    max_expansions: 3
    
  search_institutions:
    semantic_enabled: false  # Institution names are usually exact matches
    
  # List tools don't need semantic enhancement
  list_academic_documents:
    semantic_enabled: false
    
  list_chronicle_documents:
    semantic_enabled: false

# Semantic tool definitions - new tools generated specifically for semantic search
semantic_tools:
  semantic_search_chunks:
    description: "Perform semantic search across document chunks using embeddings"
    parameters:
      query: "Search query text"
      limit: "Maximum results (default: 10)"
      doc_type: "Filter by document type (academic/chronicle)"
      similarity_threshold: "Minimum similarity score (0.0-1.0, default: 0.5)"
    category: "semantic_search"
    
  find_similar_entities:
    description: "Find entities semantically similar to query using embeddings"
    parameters:
      query: "Search query text"
      entity_type: "Filter by entity type (topic/person/method/etc)"
      limit: "Maximum results (default: 15)"
      similarity_threshold: "Minimum similarity score (0.0-1.0, default: 0.5)"
    category: "semantic_search"
    
  semantic_concept_explorer:
    description: "Explore concepts using semantic similarity across all entity types"
    parameters:
      concept: "Concept to explore"
      depth: "Search depth (1-3, default: 2)"
      include_types: "Entity types to include (list)"
    category: "semantic_exploration"
    
  hybrid_search_documents:
    description: "Search documents using both keyword and semantic matching"
    parameters:
      query: "Search query"
      semantic_weight: "Weight for semantic results (0.0-1.0, default: 0.6)"
      limit: "Maximum results (default: 10)"
    category: "hybrid_search"

# Query expansion strategies
query_expansion_strategies:
  # Strategy for expanding topic searches
  topic_expansion:
    method: "semantic_similarity"
    source_embeddings: "topic_embeddings"
    expansion_templates:
      - "Related mathematical concepts"
      - "Associated research methods"
      - "Connected theoretical frameworks"
    
  # Strategy for expanding document searches  
  document_expansion:
    method: "chunk_analysis"
    source_embeddings: "chunk_embeddings"
    expansion_templates:
      - "Relevant technical terms"
      - "Domain-specific vocabulary"
      - "Methodological keywords"
      
  # Strategy for expanding people searches
  person_expansion:
    method: "collaboration_analysis"
    source_embeddings: "person_embeddings"
    expansion_templates:
      - "Research collaborators"
      - "Institutional affiliations"
      - "Co-author networks"

# Fallback and error handling
fallback_strategies:
  semantic_search_failure:
    action: "fallback_to_sql"
    log_error: true
    
  embedding_generation_failure:
    action: "disable_semantic_for_query"
    retry_count: 1
    
  low_similarity_results:
    threshold: 0.3
    action: "expand_search_terms"
    max_expansions: 2

# Performance optimization
optimization:
  caching:
    enabled: true
    cache_embeddings: true
    cache_duration_hours: 24
    
  batch_processing:
    enabled: true
    batch_size: 50
    
  early_termination:
    enabled: true
    min_results_threshold: 5  # Stop searching if we have enough good results
    
# Integration with existing blueprint tools
integration:
  # How to merge semantic and SQL results
  result_merging:
    strategy: "weighted_score"
    deduplication: true
    score_normalization: true
    
  # How to handle parameter passing
  parameter_mapping:
    semantic_search_chunks:
      query: "query"
      limit: "limit"
      doc_type: "doc_type"
      similarity_threshold: "similarity_threshold"
    
    find_similar_entities:
      query: "query" 
      entity_type: "entity_type"
      limit: "limit"
      similarity_threshold: "similarity_threshold"